export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USERS_VALID = "GET_USERS_VALID";
export const GET_EPOCH_DYNASTY = "GET_EPOCH_DYNASTY";
export const GET_TRANSACTION_HASH = 'GET_TRANSACTION_HASH';
export const GET_TRANSACTION_HASH_SUCCESS = 'GET_TRANSACTION_HASH_SUCCESS';
export const GET_TRANSACTION_HASH_FAIL = 'GET_TRANSACTION_HASH_FAIL';

export default ''